# Generated by Django 3.1.2 on 2020-10-19 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webbanhang', '0002_category_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='promo_price',
            field=models.IntegerField(default=0),
        ),
    ]
