# Generated by Django 3.1.2 on 2020-10-19 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webbanhang', '0003_product_promo_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
