# Generated by Django 3.1.2 on 2020-10-20 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webbanhang', '0004_remove_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='product_img',
            field=models.CharField(default='', max_length=255),
        ),
    ]
